# This example shows how you can send a Telegram message using Telegram Bot API.
# Telegram docs: https://core.telegram.org/bots/api#sendmessage
#
# Test with:
#
# curl "http://localhost:7055/telegram/world"
#

# All logging enabled
debug: true
listeners:

  # The route
  /telegram/:name:

    env:
      # If the program is run with the TELEGRAM_BOT_TOKEN environment
      # variable set, it will use that one, otherwise use the provided
      # string.
      TELEGRAM_BOT_TOKEN: '{{ coalesce (env "TELEGRAM_BOT_TOKEN") "123123123:xxxxxxxxxxxxxxxxxxxxx" }}'

    # For cleanliness and readability, save the Telegram payload in a tmp YAML file,
    # which will be converted to JSON later.
    files:
      payload.yaml: |
        # Replace with your chat id
        chat_id: {{ coalesce (env "TELEGRAM_CHAT_ID") "123123123" }}
        text: |
          Hello {{ .name }}!

    # Command to run, and list of arguments
    command: bash
    args:
      - -c
      # When executing bash commands, we need to set -e to propagate any errors.
      - -e
      - |
        HOOK="https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage"

        # Send the request, converting the YAML file into a JSON one on the fly, and
        # expect HTTP 200 code
        STATUS=$(curl -s -o /dev/stderr --write-out "%{http_code}" \
          -X POST -H "Content-Type: application/json" "$HOOK" --data-binary @- << EOF
        {{ fileReadToString (qv).files.payload_yaml | yamlToJson }}
        EOF
        )
        echo "Status: $STATUS"

        # Our command should succeed ONLY if we got a 200 code.
        # This will cause the script to exit with an error if
        # we have not gotten the proper status code.
        [ $STATUS -eq 200 ]

    plugins:
      # We initialize the retry plugin, and configure it to retry if we have been rate-limited
      - retry:
          condition: |
            contains "Status: 429" .__qvRetry.PreviousResult.Output
          delay: "5s"