# All logging enabled
debug: true
listeners:

  # Hello world listener
  #
  # Test with:
  #
  # [200] curl "http://localhost:7055/hello?name=Mr.%20Anderson"
  # Expect "Hello Mr. Anderson"
  #
  # [200] curl "http://localhost:7055/hello" -d '{"name":"Mr. Anderson"}' -H 'Content-Type: application/json'
  # Expect "Hello Mr. Anderson"
  #
  /hello:

    # Returns the output of the command in the response
    return: output

    # Log everything about the command execution
    log: all

    # Command to run, and list of arguments
    command: bash
    args:
      - -c
      # You can use templates to customize commands/arguments/env vars
      - |
        echo "Hello {{ .name }}"
