# All logging enabled
debug: true
listeners:

  # Tests the ability to create temporary files
  #
  # Test with
  #
  # [200] curl "http://localhost:7055/temp?name=Kitti"
  # Expect "Hello Kitti!\nHello Kitti!"
  #
  /temp:

    # Here we define our temporary file, which will be stored in a temporary path
    # and deleted after each listener execution
    files:
      tmp1: |
        Hello {{ .name }}!

    # Command to run, and list of arguments
    command: bash
    args:
      - -c
      - |
        set -e

        # Retrieve the temporary file path in different ways
        cat $QV_FILES_tmp1
        cat {{ (qv).files.tmp1 }}
