# All logging enabled
debug: true
defaults:

  # The error handler will be triggered whenever a listener
  # fails to be executed.
  #
  # This error handler creates a file, which contains an error
  # message.
  errorHandler:
    storage:
      conn: 'fs:///tmp/gotoexec-tests'
      store: output
      asYaml: true

    command: bash
    args:
      - -c
      - |
        echo "There has been an error!"

listeners:

  # This listener will cause an error because of a bad exit code
  #
  # Test with:
  # [500,ERR] curl "http://localhost:7055/crash"
  # Expect error handler result "There has been an error!"
  /crash:

    # Command to run, and list of arguments
    command: bash
    args:
      - -c
      - |
        echo "Oh no!"
        exit 1