# This example requires the defaults config `defaults.combined.echo.yaml` and the second config part `config.combined.echo.part2.notest.yaml` to be loaded via:
#
# qvalet -c config.combined.echo.yaml -c config.combined.echo.part2.notest.yaml -f defaults.combined.echo.yaml
#
# [DEFAULTS=defaults.combined.echo.yaml]
# [PART=config.combined.echo.part2.notest.yaml]

debug: true
listeners:

  # Test with:
  #
  # curl "http://localhost:7055/cow"
  # Expect "Moo!"
  #
  /cow:
    args:
      - Moo!

  # We expect also the part2 to be loaded, so you can test:
  #
  # curl "http://localhost:7055/cat"
  # Expect "Meow!"
  #