# All logging enabled
debug: true
listeners:

  # Listener with path parameter, which is accessible
  # via .param1
  #
  # Test with:
  #
  # [200] curl "http://localhost:7055/hello/world?name=Mr.%20Anderson"
  # Expect "Hello MR. ANDERSON, with param world"
  #
  # [200] curl "http://localhost:7055/hello/world" -d 'name=Mr. Anderson'
  # [200] curl "http://localhost:7055/hello/world" -d '{"name": "Mr. Anderson"}' -H 'Content-Type: application/json'
  #
  # To make it crash, pass e.g. a number instead of a string, which
  # is not supported by the `upper` function:
  # [500] curl "http://localhost:7055/hello/world" -d '{"name": 3}' -H 'Content-Type: application/json'
  # Expect error contains "wrong type for value"
  #
  /hello/:param1:

    # Returns the output of the command in the response
    return: output

    # Command to run, and list of arguments
    command: bash
    args:
      - -c
      # Expects a `name` field to be passed by query or body (JSON/Form)
      - |
        echo "Hello {{ .name | upper }}, with param {{ .param1 }}"
