# This example is part of the `config.combined.echo.yaml` config.
#
# qvalet -c config.combined.echo.yaml -c config.combined.echo.part2.notest.yaml -f defaults.combined.echo.yaml
#

debug: true
listeners:
  /cat:
    args:
      - Meow!