# This example shows how you can send a Slack message using Slack webhooks.
# Slack docs: https://slack.com/intl/en-fi/help/articles/115005265063-Incoming-webhooks-for-Slack
#
# Test with:
#
# curl "http://localhost:7055/slack/world"
#

# All logging enabled
debug: true
listeners:

  # The route
  /slack/:name:

    env:
      # If the program is run with the SLACK_HOOK environment
      # variable set, it will use that one, otherwise use the provided
      # string.
      SLACK_HOOK: '{{ coalesce (env "SLACK_HOOK") "https://hooks.slack.com/services/XXXXXXXX" }}'

    # For cleanliness and readability, save the Slack payload in a tmp YAML file,
    # which will be converted to JSON later.
    files:
      payload.yaml: |
        username: Test Slack hook from GTE!
        icon_emoji: ":jack_o_lantern:"
        text: |
          Hello {{ .name }}!
      # We store the response code to see if we need to retry (429)
      curl_status: ""

    # Command to run, and list of arguments
    command: bash
    args:
      - -c
        # When executing bash commands, we need to set -e to propagate any errors.
      - -e
      - |
        # Send the request, converting the YAML file into a JSON one on the fly, and
        # expect HTTP 200 code
        STATUS=$(curl -s -o /dev/stderr --write-out "%{http_code}" \
          -X POST -H "Content-Type: application/json" "$SLACK_HOOK" --data-binary @- << EOF
        {{ fileReadToString (gte).files.payload_yaml | yamlToJson }}
        EOF
        )
        echo -n "$STATUS" > $GTE_FILES_curl_status

        [ $STATUS -eq 200 ]

    plugins:
      # We initialize the retry plugin, and configure it to retry if we have been rate-limited
      - retry:
          condition: eq (fileReadToString (gte).files.curl_status) "429"
          delay: "5s"