# This example shows how to load a plugin, in this case the preview plugin

# All logging enabled
debug: true
listeners:

  # Test with:
  #
  # [200] curl "http://localhost:7055/hello?word=Mr.%20Anderson"
  # Expect "Hello Mr. Anderson"
  #
  #
  # To see the command preview (JSON format) use:
  #
  # [200] curl "http://localhost:7055/hello/preview?word=Mr.%20Anderson" -u qv:myPassword
  # Expect raw "{\"command\":\"echo\",\"args\":[\"Hello Mr. Anderson\"]}"
  #
  #
  # To see the command preview (YAML format, more readable) use:
  #
  # [200] curl "http://localhost:7055/hello/previewYAML?word=Mr.%20Anderson"
  # Expect raw "command: echo\nargs:\n- Hello Mr. Anderson"
  #
  # NOTE that we defined the path `/previewYAML` in the plugin configuration.
  #
  /hello:
    # Returns the output of the command in the response
    return: output

    # Command to run, and list of arguments
    command: echo
    args:
      - "Hello {{ .word }}"

    # Here is where we can define plugins to be loaded for this listener
    plugins:

      # We initialize the preview plugin, which will append a `/preview` route to the
      # listener, and you can use this route to preview the command which will be executed.
      - preview:
          # A separate authentication method can be applied for the preview plugin
          auth:
            - apiKeys:
                - myPassword
              basicAuth: true

      # We can also add another preview path, which in this case will print the result as YAML.
      - preview:
          # The generated path can be customized
          route: /previewYAML

          # When true, the output will be human-friendly, YAML-formatted.
          asYAML: true

  # The preview plugin will also tell you if a command is NOT going to be executed because
  # of any trigger condition, here is an example to show this case.
  #
  # Test with:
  #
  # curl "http://localhost:7055/trigger?name=Poinki"
  # Expect "Hello Poinki!"
  #
  # curl "http://localhost:7055/trigger?name=Arthur"
  # Expect "not triggered"
  #
  #
  # To see the command preview use:
  #
  # [200] curl "http://localhost:7055/trigger/preview?name=Poinki"
  # Expect raw "command: echo\nargs:\n- Hello Poinki!"
  #
  # To see the command preview for when the command will NOT be triggered, use:
  #
  # [200] curl "http://localhost:7055/trigger/preview?name=Arthur"
  # Expect raw "output: not triggered"
  #
  /trigger:

    trigger: eq .name "Poinki"

    command: echo
    args:
      - Hello Poinki!

    # Here is where we can define plugins to be loaded for this listener
    plugins:
      - preview:
          asYAML: true