name: Changelog
on:
  workflow_dispatch: {}
  workflow_run:
    workflows: [ "Release" ]
    types:
      - completed
jobs:
  build:
    if: |
      github.event_name == 'push' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker://githubchangeloggenerator/github-changelog-generator
        name: Generate changelog
        with:
          args: --user cmaster11 --project go-to-exec --include-tags-regex "^v\d+\.\d+.\d+$" -t ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: CHANGELOG.md
          file_pattern: CHANGELOG.md
