name: Release

# on events
on:
  push:
    tags:
      - v*

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run tests
        uses: ./.github/actions/test
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SLACK_HOOK: ${{ secrets.SLACK_HOOK }}
          GTE_LISTENERS__GCS_STORAGE_CONN: ${{ secrets.GTE_LISTENERS__GCS_STORAGE_CONN }}

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1.0.2
        env:
          CGO_ENABLED: "0"
        with:
          platforms: 'linux/386, linux/amd64, linux/arm, linux/arm64, darwin/amd64, windows/amd64'
          package: 'cmd'
          dest: 'dist'
          name: 'gotoexec'
      - name: Release
        uses: softprops/action-gh-release@v0.1.8
        with:
          files: dist/*
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm
          tags: |
            cmaster11/go-to-exec:latest
            cmaster11/go-to-exec:${{ env.TAG }}