name: Test

on:
  workflow_dispatch: {}
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - '.github/dependabot.yml'
      - 'docs/**'
      - 'README'
      - 'LICENSE'
      - 'index.html'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Test AWS SNS
      - name: Configure AWS credentials from test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Run AWS SNS test
        run: bash ./hack/test-awssns/upload.sh
        env:
          AWS_SNS_ARN: ${{ secrets.AWS_SNS_ARN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SCP_HOST: ${{ secrets.SCP_HOST }}
          SSH_KEY_BASE64: ${{ secrets.SSH_KEY_BASE64 }}

      - name: Run tests
        uses: ./.github/actions/test
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SLACK_HOOK: ${{ secrets.SLACK_HOOK }}
          GTE_LISTENERS__GCS_STORAGE_CONN: ${{ secrets.GTE_LISTENERS__GCS_STORAGE_CONN }}
