name: Test

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: [ "Dependabot PR Check" ]
    types:
      - completed
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/changelog.yml'
      - '.github/workflows/dependabot-wf.yml'
      - '.github/workflows/release.yml'
      - 'docs/**'
      - '.husky/**'
      - 'hack/autosidebar/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'index.html'

jobs:
  test:

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    if: ${{ !((github.event_name == 'push' && github.actor == 'dependabot[bot]') || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion != 'success')) }}
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Test AWS SNS
      - name: Configure AWS credentials from test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Run tests
        uses: ./.github/actions/test
        env:
          QV_DEFAULTS_DATABASE_HOST: postgres
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SLACK_HOOK: ${{ secrets.SLACK_HOOK }}
          QV_LISTENERS__GCS_STORAGE_CONN: ${{ secrets.QV_LISTENERS__GCS_STORAGE_CONN }}
          AWS_SNS_ARN: ${{ secrets.AWS_SNS_ARN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}