name: Test

on:
  workflow_dispatch: {}
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Run tests
        uses: ./.github/actions/test
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SLACK_HOOK: ${{ secrets.SLACK_HOOK }}